### ISSUE TITLE
How to validate a web and api request with JWT Token?

### ISSUE THREAD

**Issue by SatyaRamprasad** [explorer14/JwtAuthenticationHelper#1]

**Comment by explorer14** [comment]
Hi, I am not sure I understand your question. Can you please provide a bit more detail on your specific problem?

**Comment by SatyaRamprasad** [comment]
Hi @explorer14 
Thanks for the reply.

How would i validate an actionresult/method using JWT?
In your project you didn't used any attributes to check other than Authorize to validate a request.
Can i use this attribute [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)] to check token is valid?
When i use this, i am getting the response as Unauthorized.

**Comment by explorer14** [comment]
Well, the validation of the token is pretty much the default ASP.NET Core behaviour when you add JWT bearer auth (for APIs). For web apps, when using cookies with the JWT, you need to provide an implementation for `ISecureDataFormat<AuthenticationTicket>` as I have done in this package that will then validate the secure cookie to see if the underlying token is still valid or not. The `Authorize` attribute is generally enough to tell the ASP.NET Core that it needs to use the configured authentication mechanism to authenticate incoming requests, so it should work as is.

Hope this helps.

**Comment by Weboholics** [comment]
I think I found a bug in your code regarding iat in your function **MergeUserClaimsWithDefaultClaims**

//I think this is incorrect - should be seconds since 1970
new Claim(JwtRegisteredClaimNames.Iat, DateTime.UtcNow.TimeOfDay.Ticks.ToString(), ClaimValueTypes.Integer64)

//My fix
long seconds = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
new Claim(JwtRegisteredClaimNames.Iat,seconds.ToString(),ClaimValueTypes.Integer64)
